[project]
name = "token-view"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.5.2",
    "asttokens>=3.0.0",
    "bitsandbytes>=0.45.3",
    "fastapi>=0.115.11",
    "openai>=2.14.0",
    "rich>=14.0.0",
    "torch>=2.6.0",
    "transformers>=4.49.0",
    "tree-sitter>=0.25.2",
    "tree-sitter-python>=0.25.0",
    "uvicorn[standard]>=0.34.0",
]
